FROM node:13
WORKDIR /app/client/
COPY package.json .
RUN npm install -g typescript
RUN npm install
RUN npm rebuild node-sass
COPY . .
ENV CHOKIDAR_USEPOLLING=true
ENV HOST_API "http://localhost:3000/api"
ENV HOST_IMAGE "http://localhost:3000/api/static"
CMD ["npm", "run",  "deploy"]