FROM node:13
WORKDIR /app/client/
COPY package.json .
RUN npm install -g typescript
RUN npm install
RUN npm rebuild node-sass
COPY . .
ENV CHOKIDAR_USEPOLLING=true
ENV HOST_API "/api"
ENV HOST_IMAGE "/api/static"

# CMD ["npm", "run",  "production"]
CMD ["npm", "run",  "dev"]