version: '3'
services:
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'
      - '5000:5000'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/server/node_modules
      - ./server:/app/server
  admin:
    depends_on: 
      - api
    build: 
      dockerfile: Dockerfile.dev
      context: ./admin
    volumes:
      - /app/admin/node_modules
      - ./admin:/app/admin                   
  client:
    depends_on: 
      - api
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /.next 
      - /app/client/node_modules
      - ./client:/app/client
    
