version: '3'
services:
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'
      - '5000:5000'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/server/node_modules
      - ./server:/app/server
    env_file: 
      ./env/server.env       
  admin:
    depends_on: 
      - api
    build: 
      dockerfile: Dockerfile.dev
      context: ./admin
    volumes:
      - /app/admin/node_modules
      - ./admin:/app/admin
    env_file: 
      ./env/admin.env                       
  client:
    depends_on: 
      - api
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/client/.next
      - /app/client/node_modules
      - ./client:/app/client
    env_file: 
      ./env/client.env  
    
