apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers: 
        - name: client
          image: sidorov/imed-client
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: HOST_API
              valueFrom: 
                secretKeyRef:
                  name: hostapi
                  key: HOST_API
            - name: HOST_IMAGE
              valueFrom: 
                secretKeyRef:
                  name: hostimage
                  key: HOST_IMAGE        

