/*General*/
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const TOGGLE_MENU_MOBILE = 'TOGGLE_MENU_MOBILE';
export const TOGGLE_ANCHOR = 'TOGGLE_ANCHOR';

/*Forms*/
export const TOGGLE_FORM_VACANCY = 'TOGGLE_FORM_VACANCY';
export const TOGGLE_FORM_FEEDBACK = 'TOGGLE_FORM_FEEDBACK';
export const TOGGLE_FORM_SEMINAR = 'TOGGLE_FORM_SEMINAR';
export const TOGGLE_FORM_SIGN = 'TOGGLE_FORM_SIGN';

/*Requests*/
export const FETCH_SALES_REQUEST = 'FETCH_SALES_REQUEST';
export const LOADING_SALES_REQUEST = 'LOADING_SALES_REQUEST';

export const FETCH_DOCTORS_REQUEST = 'FETCH_DOCTORS_REQUEST';
export const LOADING_DOCTORS_REQUEST = 'LOADING_DOCTORS_REQUEST';

export const FETCH_FEEDBACKS_REQUEST = 'FETCH_FEEDBACKS_REQUEST';
export const LOADING_FEEDBACKS_REQUEST = 'LOADING_FEEDBACKS_REQUEST';

export const FETCH_BANNERS_REQUEST = 'FETCH_BANNERS_REQUEST';
export const LOADING_BANNERS_REQUEST = 'LOADING_BANNERS_REQUEST';

export const LOADING_ABOUT_REQUEST = 'LOADING_ABOUT_REQUEST';
export const FETCH_ABOUT_REQUEST = 'FETCH_ABOUT_REQUEST';

export const FETCH_PHOTO_REQUEST = 'FETCH_PHOTO_REQUEST';
export const LOADING_PHOTO_REQUEST = 'LOADING_PHOTO_REQUEST';

export const LOADING_VIDEO_REQUEST = 'LOADING_VIDEO_REQUEST';
export const FETCH_VIDEO_REQUEST = 'FETCH_VIDEO_REQUEST';

export const LOADING_DOCTOR_REQUEST = 'LOADING_DOCTOR_REQUEST';
export const FETCH_DOCTOR_REQUEST = 'FETCH_DOCTOR_REQUEST';

export const LOADING_SERVICES_REQUEST = 'LOADING_SERVICES_REQUEST';
export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';

export const LOADING_VACANCIES_REQUEST = 'LOADING_VACANCIES_REQUEST';
export const FETCH_VACANCIES_REQUEST = 'FETCH_VACANCIES_REQUEST';

export const LOADING_SERVICE_REQUEST = 'LOADING_SERVICE_REQUEST';
export const FETCH_SERVICE_REQUEST = 'FETCH_SERVICE_REQUEST';

export const LOADING_SALE_REQUEST = 'LOADING_SALE_REQUEST';
export const FETCH_SALE_REQUEST = 'FETCH_SALE_REQUEST';

export const LOADING_ARTICLES_REQUEST = 'LOADING_ARTICLES_REQUEST';
export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';

export const LOADING_EVENT_REQUEST = 'LOADING_EVENT_REQUEST';
export const FETCH_EVENT_REQUEST = 'FETCH_EVENT_REQUEST';

export const LOADING_DESC_REQUEST = 'LOADING_DESC_REQUEST';
export const FETCH_DESC_REQUEST = 'FETCH_DESC_REQUEST';

export const LOADING_SCHEDULE_REQUEST = 'LOADING_SHEDULE_REQUEST';
export const FETCH_SCHEDULE_REQUEST = 'FETCH_SHEDULE_REQUEST';

export const SENDING_FORM = 'SENDING_FORM';
export const FORM_SUCCESS = 'FORM_SUCCESS';
export const FORM_FAILED = 'FORM_FAILED';
